

CREATE Role notepad_app with Login password 'app123';


GRANT CONNECT on database notepad to notepad_app;

GRANT USAGE on SCHEMA public to notepad_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO notepad_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO notepad_app;


ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO notepad_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO notepad_app;

CREATE SCHEMA dbo;
GRANT USAGE on SCHEMA dbo to notepad_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA dbo TO notepad_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA dbo TO notepad_app;


ALTER DEFAULT PRIVILEGES IN SCHEMA dbo
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO notepad_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA dbo
    GRANT USAGE, SELECT ON SEQUENCES TO notepad_app;
